### ISSUE TITLE
how to notify work interface stop ? 

### ISSUE THREAD

**Issue by leeonsoft** [ahmetask/worker#10]
Is it possible to add a stop interface to the interface of the work interface? If the do method is a long loop, I don't know how to cancel the current work

**Comment by ahmetask** [comment]
Hi @leeonsoft, Thanks for bringing up yes you are right there is no interface function to stop current work progress but what you can do is you can pass cancel context to your custom work. I am sharing an example of how to do that but ideally, the worker should wait for your work regardless of what happens. Work management belongs to the user. If you can share your example I may suggest an alternative solution or We can improve the worker library accordingly. Thank you btw you gave me an idea to implement another Worker Type with Do function that if work is not finished given a specific time it can give up

```go
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"time"

	"github.com/ahmetask/worker"
)

type Job struct {
	Context context.Context
}

func (j *Job) Do() {
	defer func() {
		fmt.Println("job finished")
	}()
	for {
		select {
		case <-j.Context.Done():
			fmt.Println(j.Context.Err())
			return
		default:
			time.Sleep(1 * time.Second)
			fmt.Println("work load")
		}
	}
}

func main() {
	pool := worker.NewWorkerPool(4, 4)
	pool.Start()

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)

	pool.Submit(&Job{Context: ctx})

	time.Sleep(2 * time.Second)
	cancel()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, os.Interrupt)
	<-quit
	pool.Stop()
}



```

**Comment by leeonsoft** [comment]
hi @ahmetask thanks .I added a stop method to the work, and at the same time I added a reference to works[]Work in the dispatcher.go object to ensure that after receiving the termination command, broadcast to the work and request the work's stop interface, and then Just notify the work, and the work decides how to deal with the actual situation
[worker.zip](https://github.com/ahmetask/worker/files/8395666/worker.zip)

**Comment by ahmetask** [comment]
Hi, @leeonsoft could you please open a pull request so that we can go through it

**Comment by ahmetask** [comment]
Thank you for your suggestions 
just a quick note @leeonsoft works array is in the critical section so please be careful.

I am not sure it's required and correct solution 

even if you call the stop function worker waits for previous work to be terminated
```go
func (w *worker) Start() {
	go func() {
		w.done.Add(1) 
		for {
			w.readyPool <- w.work
			select {
			case work := <-w.work: 
				w.Process(work) // processing
			case <-w.quit:   // waits for next loop it means current process needs to be finish 
				w.done.Done() 
				return
			}
		}
	}()
}
```

**Comment by leeonsoft** [comment]
hi @asikahmet  After adjusting the code, I use it like this, please refer to it. thank you very much

```go
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"testworker/worker"
	"time"
)

type longJob struct {
	quit bool
}

func (l *longJob) doWork() {
	fmt.Println(time.Now())
}

func (l *longJob) Do() {
	for {
		if l.quit == true {
			fmt.Println("goroutine is break ")
			break
		}
		l.doWork()
	}
}

func (l *longJob) Stop() {
	l.quit = true
}

func main() {
	pool := worker.NewWorkerPool(100, 100)
	pool.Start()
	for i := 0; i < 10; i++ {
		Job := &longJob{}
		pool.Enqueue(Job)
	}
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, os.Interrupt, syscall.SIGTERM, syscall.SIGKILL)
	<-quit
	pool.Stop()
	fmt.Println("exit...")
}
```

**Comment by ahmetask** [comment]
Hi @leeonsoft I review your changes [above](https://github.com/ahmetask/worker/issues/10#issuecomment-1085555506) but here is the detailed review. also please open pr in this way we can review easily 

- Submit method can be used in multiple goroutines so q.works is in the critical section (it`s similar for Enquee and EnqueueWithTimeout)
- and you are not removing works from the q.works array it will overflow eventually. you can use map with locks and then you can remove it in Start function

- below you can find suggestions 
```go
func (q *Pool) Submit(job Work) {
	// critical section start
	q.works = append(q.works, job) //add by James
	// suggestion:  keep this array or map in the worker. it won't be in critical section
	// critical section end
	q.singleJob <- job
}

func (w *worker) Start() {
	go func() {
		w.done.Add(1) 
		for {
			w.readyPool <- w.work 
			select {
			case work := <-w.work: 
			        // suggestion: add work to w.works array
				w.Process(work)  
				// suggestion:  remove work from w.works array or map
			case <-w.quit:
				w.done.Done()
				return
			}
		}
	}()
}

```




please feel free to fork and use this solution but ideally, the worker needs to wait for your work.

**Comment by ahmetask** [comment]
@leeonsoft here I opened a pr but I am not sure yet. I just wanted to give you an idea 
https://github.com/ahmetask/worker/pull/11

**Comment by leeonsoft** [comment]
@ahmetask Thank you very much, your pr can meet my requirements, this issue can be closed. Thank you again
