### ISSUE TITLE
for-select in dispatcher.go:EnqueueWithTimeout

### ISSUE THREAD

**Issue by waffleboot** [ahmetask/worker#7]
Hi

Could you please explain what is a reason to use for-select in EnqueueWithTimeout@dispatcher.go ?

Why not

```
select {
    case q.internalQueue <- job:
        return true
    case <- time.After(timeout):
        return false
}
```

**Comment by ahmetask** [comment]
Hi @waffleboot because it's infinite loop it needs to check internalQueue channels until timeout occurs

**Comment by waffleboot** [comment]
Hi @ahmetask 

I still don't understand why we need infinite loop here. If we unable to send job to internalQueue and there is no timeout then select{} will be blocked. As I know for-select is used when we constantly read/write from/to channels but there I see return stmt.

I understand when we don't return
```
for {
	select {
	case val := <- ch:
		fmt.Println(val)
	case <-time.After(timeout):
		return
	}
}
```
but there we return after sending job to channel.

**Comment by ahmetask** [comment]
thanks for the heads up. Its misusage of select. We can delete for loop although it is not critical.
