### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by waffleboot** [ahmetask/worker#8]
```
goroutine 33 [running]:
github.com/ahmetask/worker.(*Pool).EnqueueWithTimeout.func1()
        /root/go/src/github com/ahmetask/worker/dispatcher.go:106 +0x36
created by time.goFunc
        /usr/local/go/src/time/sleep.go:166 +0x45
```

test case:

```
q.internalQueue <- job
return
run defer
t.Stop()
close(ch)
```

at the same time timer is fired just by timeout. It's race condition: defer vs timer's func
`ch <- false // but ch is closed yet`

timer.Stop doesn't stop timer really, it marks it as stopped only and timer will be deleted by goroutine that created that timer.

[time.go deltimer func with comment](https://cs.opensource.google/go/go/+/master:src/runtime/time.go;l=306)

**Comment by ahmetask** [comment]
thanks we can delete  [close(ch)](https://github.com/ahmetask/worker/blob/master/dispatcher.go#L109) and leave it to the gc
